/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DNSRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteRecord"
      | "fidRegistry"
      | "getRecord"
      | "getRecordNames"
      | "owner"
      | "recordExists"
      | "recordExistsFor"
      | "recordNames"
      | "records"
      | "renounceOwnership"
      | "setFIDRegistry"
      | "setRecord"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RecordDeleted"
      | "RecordSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteRecord",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fidRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordNames",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordExists",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordExistsFor",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordNames",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFIDRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecord",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fidRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordExistsFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFIDRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordDeletedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    recordType: BigNumberish,
    name: string
  ];
  export type OutputTuple = [tokenId: bigint, recordType: bigint, name: string];
  export interface OutputObject {
    tokenId: bigint;
    recordType: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordSetEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    recordType: BigNumberish,
    name: string,
    value: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    recordType: bigint,
    name: string,
    value: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    recordType: bigint;
    name: string;
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DNSRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DNSRegistry;
  waitForDeployment(): Promise<this>;

  interface: DNSRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteRecord: TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish, name: string],
    [void],
    "nonpayable"
  >;

  fidRegistry: TypedContractMethod<[], [string], "view">;

  getRecord: TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish, name: string],
    [string],
    "view"
  >;

  getRecordNames: TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordExists: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: string],
    [boolean],
    "view"
  >;

  recordExistsFor: TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish, name: string],
    [boolean],
    "view"
  >;

  recordNames: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;

  records: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: string],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFIDRegistry: TypedContractMethod<
    [_fidRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setRecord: TypedContractMethod<
    [
      tokenId: BigNumberish,
      recordType: BigNumberish,
      name: string,
      value: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fidRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish, name: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordNames"
  ): TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordExists"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordExistsFor"
  ): TypedContractMethod<
    [tokenId: BigNumberish, recordType: BigNumberish, name: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordNames"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFIDRegistry"
  ): TypedContractMethod<[_fidRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecord"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      recordType: BigNumberish,
      name: string,
      value: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecordDeleted"
  ): TypedContractEvent<
    RecordDeletedEvent.InputTuple,
    RecordDeletedEvent.OutputTuple,
    RecordDeletedEvent.OutputObject
  >;
  getEvent(
    key: "RecordSet"
  ): TypedContractEvent<
    RecordSetEvent.InputTuple,
    RecordSetEvent.OutputTuple,
    RecordSetEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecordDeleted(uint256,uint8,string)": TypedContractEvent<
      RecordDeletedEvent.InputTuple,
      RecordDeletedEvent.OutputTuple,
      RecordDeletedEvent.OutputObject
    >;
    RecordDeleted: TypedContractEvent<
      RecordDeletedEvent.InputTuple,
      RecordDeletedEvent.OutputTuple,
      RecordDeletedEvent.OutputObject
    >;

    "RecordSet(uint256,uint8,string,string)": TypedContractEvent<
      RecordSetEvent.InputTuple,
      RecordSetEvent.OutputTuple,
      RecordSetEvent.OutputObject
    >;
    RecordSet: TypedContractEvent<
      RecordSetEvent.InputTuple,
      RecordSetEvent.OutputTuple,
      RecordSetEvent.OutputObject
    >;
  };
}
