/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FIDResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dnsRegistry"
      | "fidRegistry"
      | "fidToUsername"
      | "getDNSRecordByFID"
      | "getDNSRecordByUsername"
      | "getFIDByUsername"
      | "getUsername"
      | "registerUsername"
      | "resolveFID"
      | "resolveUsername"
      | "usernameToFID"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "UsernameRegistered" | "UsernameUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dnsRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fidRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fidToUsername",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDNSRecordByFID",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDNSRecordByUsername",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFIDByUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUsername",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUsername",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveFID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "usernameToFID",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "dnsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fidRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fidToUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDNSRecordByFID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDNSRecordByUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFIDByUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveFID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usernameToFID",
    data: BytesLike
  ): Result;
}

export namespace UsernameRegisteredEvent {
  export type InputTuple = [fid: BigNumberish, username: string];
  export type OutputTuple = [fid: bigint, username: string];
  export interface OutputObject {
    fid: bigint;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameUpdatedEvent {
  export type InputTuple = [
    fid: BigNumberish,
    oldUsername: string,
    newUsername: string
  ];
  export type OutputTuple = [
    fid: bigint,
    oldUsername: string,
    newUsername: string
  ];
  export interface OutputObject {
    fid: bigint;
    oldUsername: string;
    newUsername: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FIDResolver extends BaseContract {
  connect(runner?: ContractRunner | null): FIDResolver;
  waitForDeployment(): Promise<this>;

  interface: FIDResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dnsRegistry: TypedContractMethod<[], [string], "view">;

  fidRegistry: TypedContractMethod<[], [string], "view">;

  fidToUsername: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getDNSRecordByFID: TypedContractMethod<
    [fid: BigNumberish, recordType: BigNumberish, name: string],
    [string],
    "view"
  >;

  getDNSRecordByUsername: TypedContractMethod<
    [username: string, recordType: BigNumberish, name: string],
    [string],
    "view"
  >;

  getFIDByUsername: TypedContractMethod<[username: string], [bigint], "view">;

  getUsername: TypedContractMethod<[fid: BigNumberish], [string], "view">;

  registerUsername: TypedContractMethod<
    [fid: BigNumberish, username: string],
    [void],
    "nonpayable"
  >;

  resolveFID: TypedContractMethod<[fid: BigNumberish], [bigint], "view">;

  resolveUsername: TypedContractMethod<[username: string], [bigint], "view">;

  usernameToFID: TypedContractMethod<[arg0: string], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dnsRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fidRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fidToUsername"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDNSRecordByFID"
  ): TypedContractMethod<
    [fid: BigNumberish, recordType: BigNumberish, name: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDNSRecordByUsername"
  ): TypedContractMethod<
    [username: string, recordType: BigNumberish, name: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFIDByUsername"
  ): TypedContractMethod<[username: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUsername"
  ): TypedContractMethod<[fid: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerUsername"
  ): TypedContractMethod<
    [fid: BigNumberish, username: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveFID"
  ): TypedContractMethod<[fid: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveUsername"
  ): TypedContractMethod<[username: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "usernameToFID"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;

  getEvent(
    key: "UsernameRegistered"
  ): TypedContractEvent<
    UsernameRegisteredEvent.InputTuple,
    UsernameRegisteredEvent.OutputTuple,
    UsernameRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "UsernameUpdated"
  ): TypedContractEvent<
    UsernameUpdatedEvent.InputTuple,
    UsernameUpdatedEvent.OutputTuple,
    UsernameUpdatedEvent.OutputObject
  >;

  filters: {
    "UsernameRegistered(uint256,string)": TypedContractEvent<
      UsernameRegisteredEvent.InputTuple,
      UsernameRegisteredEvent.OutputTuple,
      UsernameRegisteredEvent.OutputObject
    >;
    UsernameRegistered: TypedContractEvent<
      UsernameRegisteredEvent.InputTuple,
      UsernameRegisteredEvent.OutputTuple,
      UsernameRegisteredEvent.OutputObject
    >;

    "UsernameUpdated(uint256,string,string)": TypedContractEvent<
      UsernameUpdatedEvent.InputTuple,
      UsernameUpdatedEvent.OutputTuple,
      UsernameUpdatedEvent.OutputObject
    >;
    UsernameUpdated: TypedContractEvent<
      UsernameUpdatedEvent.InputTuple,
      UsernameUpdatedEvent.OutputTuple,
      UsernameUpdatedEvent.OutputObject
    >;
  };
}
