/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DNSRegistry } from "./DNSRegistry";
export type { FIDRegistry } from "./FIDRegistry";
export type { FIDResolver } from "./FIDResolver";
