/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DNSRegistry__factory } from "./DNSRegistry__factory";
export { FIDRegistry__factory } from "./FIDRegistry__factory";
export { FIDResolver__factory } from "./FIDResolver__factory";
